from __future__ import annotations

import unittest

from python.cti_engine.modules import register_builtin_modules
from python.cti_engine.registry import ModuleRegistry


class RegistryTests(unittest.TestCase):
    def test_builtin_modules_register(self) -> None:
        registry = ModuleRegistry()
        register_builtin_modules(registry)
        self.assertTrue(registry.has("adblock"))
        self.assertTrue(registry.has("ahmia"))
        self.assertTrue(registry.has("account-finder"))
        self.assertTrue(registry.has("apivoid"))
        self.assertTrue(registry.has("archive-org"))
        self.assertTrue(registry.has("abuse-ch"))
        self.assertTrue(registry.has("abuseipdb"))
        self.assertTrue(registry.has("alienvault"))
        self.assertTrue(registry.has("alienvault-ip-rep"))
        self.assertTrue(registry.has("azure-blob-finder"))
        self.assertTrue(registry.has("base64"))
        self.assertTrue(registry.has("binary-string-extractor"))
        self.assertTrue(registry.has("bgpview"))
        self.assertTrue(registry.has("blocklistde"))
        self.assertTrue(registry.has("botvrij"))
        self.assertTrue(registry.has("certspotter"))
        self.assertTrue(registry.has("censys"))
        self.assertTrue(registry.has("cinsscore"))
        self.assertTrue(registry.has("cleantalk"))
        self.assertTrue(registry.has("coinblocker"))
        self.assertTrue(registry.has("commoncrawl"))
        self.assertTrue(registry.has("company-name-extractor"))
        self.assertTrue(registry.has("country-name-extractor"))
        self.assertTrue(registry.has("crobat"))
        self.assertTrue(registry.has("crt-sh"))
        self.assertTrue(registry.has("cross-referencer"))
        self.assertTrue(registry.has("custom-threat-feed"))
        self.assertTrue(registry.has("cmseek"))
        self.assertTrue(registry.has("cybercrimetracker"))
        self.assertTrue(registry.has("dns-bruteforce"))
        self.assertTrue(registry.has("dns-lookaside"))
        self.assertTrue(registry.has("dnsgrep"))
        self.assertTrue(registry.has("dnsdumpster"))
        self.assertTrue(registry.has("dns-raw"))
        self.assertTrue(registry.has("dnsresolve"))
        self.assertTrue(registry.has("dnstwist"))
        self.assertTrue(registry.has("dns-zone-transfer"))
        self.assertTrue(registry.has("do-space-finder"))
        self.assertTrue(registry.has("dronebl"))
        self.assertTrue(registry.has("duckduckgo"))
        self.assertTrue(registry.has("emailrep"))
        self.assertTrue(registry.has("emergingthreats"))
        self.assertTrue(registry.has("file-metadata-extractor"))
        self.assertTrue(registry.has("flickr"))
        self.assertTrue(registry.has("fortiguard"))
        self.assertTrue(registry.has("gcs-finder"))
        self.assertTrue(registry.has("grep-app"))
        self.assertTrue(registry.has("github"))
        self.assertTrue(registry.has("greynoise"))
        self.assertTrue(registry.has("greensnow"))
        self.assertTrue(registry.has("hackertarget"))
        self.assertTrue(registry.has("haveibeenpwned"))
        self.assertTrue(registry.has("human-name-extractor"))
        self.assertTrue(registry.has("hunter"))
        self.assertTrue(registry.has("ipinfo"))
        self.assertTrue(registry.has("ipqualityscore"))
        self.assertTrue(registry.has("ipregistry"))
        self.assertTrue(registry.has("isc-sans"))
        self.assertTrue(registry.has("interesting-file-finder"))
        self.assertTrue(registry.has("jsonwhois"))
        self.assertTrue(registry.has("junk-file-finder"))
        self.assertTrue(registry.has("leakix"))
        self.assertTrue(registry.has("maltiverse"))
        self.assertTrue(registry.has("malwarepatrol"))
        self.assertTrue(registry.has("mnemonic-pdns"))
        self.assertTrue(registry.has("multiproxy"))
        self.assertTrue(registry.has("nbtscan"))
        self.assertTrue(registry.has("nmap"))
        self.assertTrue(registry.has("nuclei"))
        self.assertTrue(registry.has("onionsearchengine"))
        self.assertTrue(registry.has("onesixtyone"))
        self.assertTrue(registry.has("opennic"))
        self.assertTrue(registry.has("open-pdns"))
        self.assertTrue(registry.has("openphish"))
        self.assertTrue(registry.has("passivedns"))
        self.assertTrue(registry.has("pgp-keyservers"))
        self.assertTrue(registry.has("phishstats"))
        self.assertTrue(registry.has("phishtank"))
        self.assertTrue(registry.has("port-scanner-tcp"))
        self.assertTrue(registry.has("retire-js"))
        self.assertTrue(registry.has("robtex"))
        self.assertTrue(registry.has("scylla"))
        self.assertTrue(registry.has("searchcode"))
        self.assertTrue(registry.has("securitytrails"))
        self.assertTrue(registry.has("s3-finder"))
        self.assertTrue(registry.has("shodan"))
        self.assertTrue(registry.has("spamcop"))
        self.assertTrue(registry.has("spamhaus"))
        self.assertTrue(registry.has("snallygaster"))
        self.assertTrue(registry.has("sorbs"))
        self.assertTrue(registry.has("stevenblackhosts"))
        self.assertTrue(registry.has("surbl"))
        self.assertTrue(registry.has("ssl-analyzer"))
        self.assertTrue(registry.has("crxcavator"))
        self.assertTrue(registry.has("tld-searcher"))
        self.assertTrue(registry.has("talos-intelligence"))
        self.assertTrue(registry.has("threatcrowd"))
        self.assertTrue(registry.has("threatfox"))
        self.assertTrue(registry.has("threatminer"))
        self.assertTrue(registry.has("torch"))
        self.assertTrue(registry.has("torexits"))
        self.assertTrue(registry.has("testssl"))
        self.assertTrue(registry.has("trufflehog"))
        self.assertTrue(registry.has("uceprotect"))
        self.assertTrue(registry.has("urlscan"))
        self.assertTrue(registry.has("virustotal"))
        self.assertTrue(registry.has("voipbl"))
        self.assertTrue(registry.has("vxvault"))
        self.assertTrue(registry.has("viewdns"))
        self.assertTrue(registry.has("wafw00f"))
        self.assertTrue(registry.has("wappalyzer"))
        self.assertTrue(registry.has("web-spider"))
        self.assertTrue(registry.has("wikipedia-edits"))
        self.assertTrue(registry.has("wikileaks"))
        self.assertTrue(registry.has("whatweb"))
        self.assertTrue(registry.has("whoisology"))
        self.assertTrue(registry.has("whoxy"))
        self.assertTrue(registry.has("zoneh"))


if __name__ == "__main__":
    unittest.main()
